name: .NET CI Pipeline

on:
  push:
    branches: [ "main", "Backend2" ] # Đã thêm nhánh Backend2 của bạn
  pull_request:
    branches: [ "main", "Backend2" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BACKEND/TuneVault # Trỏ đúng vào thư mục chứa code của bạn

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Source Code
      run: dotnet build --no-restore --configuration Release

    # Nếu project chưa có Unit Test thì bạn hãy thêm dấu # trước 2 dòng dưới để tắt nó đi nhé
    - name: Run Unit Tests
      run: dotnet test --no-build --configuration Release --verbosity normal
